# Generated by Django 5.2.13 on 2026-08-22 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=150, verbose_name='Kategoriya nomi (UZ)')),
                ('name_ru', models.CharField(max_length=150, verbose_name='Название категории (RU)')),
                ('name_en', models.CharField(max_length=150, verbose_name='Category Name (EN)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Taom nomi (UZ)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название блюда (RU)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Dish Name (EN)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi (UZS)')),
                ('portion_weight', models.PositiveIntegerField(default=300, help_text="Porsiya og'irligi grammda (masalan, 350)", verbose_name='Porsiya vazni (g)')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Kaloriya (kcal)')),
                ('protein', models.DecimalField(decimal_places=1, default=0.0, max_digits=6, verbose_name='Oqsil / Protein (g)')),
                ('fat', models.DecimalField(decimal_places=1, default=0.0, max_digits=6, verbose_name="Yog' / Fat (g)")),
                ('carbs', models.DecimalField(decimal_places=1, default=0.0, max_digits=6, verbose_name='Uglevod / Carbs (g)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Tashqi rasm havolasi (ixtiyoriy)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Mavjud / Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
