# Generated by Django 5.2.13 on 2026-08-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Category Name (EN)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Название категории (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif (UZ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='Tashqi rasm havolasi (ixtiyoriy)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Dish Name (EN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название блюда (RU)'),
        ),
    ]
