# Generated by Django 5.1.15 on 2026-09-04 11:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def blank_out_null_image_urls(apps, schema_editor):
    """image_url becomes NOT NULL below; collapse existing NULLs to '' first."""
    Product = apps.get_model('menu', 'Product')
    Product.objects.filter(image_url__isnull=True).update(image_url='')


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_product_options_product_is_recommended_and_more'),
    ]

    operations = [
        migrations.RunPython(blank_out_null_image_urls, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol holati'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Uglevod / Carbs (g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Yog' / Fat (g)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Tashqi rasm havolasi (ixtiyoriy)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Mavjud / Faol'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Narxi (UZS)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Oqsil / Protein (g)'),
        ),
    ]
